name: kinder_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^4.0.0
  pinput: ^5.0.2
  flutter_screenutil: ^5.9.3
  go_router: ^16.2.5
  easy_localization: ^3.0.8
  sembast: ^3.8.5+1
  get_it: ^9.0.5
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.0
  google_fonts: ^6.3.2
  animate_do: ^4.2.0
  font_awesome_flutter: ^10.9.1
  gap: ^3.0.1
  supabase_flutter: ^2.10.3
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0
  get_storage: ^2.1.1
  string_validator: ^1.2.0
  multiple_result: ^5.2.0
  dart_mappable: ^4.6.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  dart_mappable_builder: ^4.6.1

flutter:
  uses-material-design: true
  assets:
    - .env



